name: Animal Nutrition API Deployment
description: Hayvan beslenme bilgileri API servisi deployment

on:
  push:
    branches: [main, master]
  manual: true

jobs:
  deploy:
    name: Deploy to Smithery
    runs-on: smithery-runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test-nutrition
        continue-on-error: true
        
      - name: Build application
        run: npm run build
        continue-on-error: true
        
      - name: Deploy to Smithery
        uses: smithery/deploy-action@v1
        with:
          api-key: ${{ secrets.SMITHERY_API_KEY }}
          project-id: animal-nutrition-api
          health-check: /health
          
      - name: Verify deployment
        run: |
          sleep 30
          curl -f https://animal-nutrition-api.smithery.app/health
          curl -f "https://animal-nutrition-api.smithery.app/animal-nutrition?animal=aslan"
          
      - name: Notify success
        if: success()
        run: echo "✅ Deployment successful!"
        
      - name: Notify failure
        if: failure()
        run: echo "❌ Deployment failed!" 